In [3]:
import numpy as np

def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

print(numpysum(2))

[0 2]


In [2]:
import pandas  as pd
from pandas import Series, DataFrame

In [4]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])
obj2
obj2.index
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj2['a']

-5

In [9]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [10]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [11]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [12]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [15]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [5]:
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data[0]=None

In [7]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [9]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
              [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = NA

In [16]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
df = pd.DataFrame(np.random.randn(7, 3))

In [19]:
df 

0         1         2
0 -0.733762  1.633531  2.536959
1 -1.483933  0.673927 -1.261877
2  0.390734 -0.764673  0.517024
3  0.595559  0.562193  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [20]:
df.iloc[:4, 1] = NA
df

0         1         2
0 -0.733762       NaN  2.536959
1 -1.483933       NaN -1.261877
2  0.390734       NaN  0.517024
3  0.595559       NaN  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [21]:
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.733762       NaN       NaN
1 -1.483933       NaN       NaN
2  0.390734       NaN  0.517024
3  0.595559       NaN  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [22]:
df.dropna()

0         1         2
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [23]:
df.dropna(thresh=2)

0         1         2
2  0.390734       NaN  0.517024
3  0.595559       NaN  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [24]:
df.fillna(0)

0         1         2
0 -0.733762  0.000000  0.000000
1 -1.483933  0.000000  0.000000
2  0.390734  0.000000  0.517024
3  0.595559  0.000000  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [25]:
df.fillna({1: 0.5, 2: 0})
df

0         1         2
0 -0.733762       NaN       NaN
1 -1.483933       NaN       NaN
2  0.390734       NaN  0.517024
3  0.595559       NaN  0.962359
4  0.273106  0.550762 -0.145859
5  0.767378 -0.066348  0.392528
6  0.233531  1.388220  1.204202

In [26]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                                  'Pastrami', 'corned beef', 'Bacon',
                                  'pastrami', 'honey ham', 'nova lox'],
                         'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
data.index[3]

3

In [29]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [30]:
lowercased = data['food'].str.lower()

In [31]:
data['food']

0          bacon
1    pulled pork
2          bacon
3       Pastrami
4    corned beef
5          Bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [32]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [33]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [34]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                        index=['Ohio', 'Colorado', 'New York'],
                        columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [35]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [36]:
data.index

Index(['Ohio', 'Colorado', 'New York'], dtype='object')

In [37]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [38]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [39]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [40]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [41]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [42]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)    

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [43]:
import numpy as np
data = np.random.rand(20)
data

array([0.60644836, 0.70322274, 0.68448221, 0.76852959, 0.78689582,
       0.979673  , 0.30868911, 0.56166321, 0.20288398, 0.09645826,
       0.82411868, 0.45765006, 0.23049113, 0.81445388, 0.98864258,
       0.68126348, 0.3702463 , 0.7622349 , 0.83049553, 0.12341142])

In [44]:
pd.cut(data, 4, precision=2)

[(0.54, 0.77], (0.54, 0.77], (0.54, 0.77], (0.77, 0.99], (0.77, 0.99], ..., (0.54, 0.77], (0.32, 0.54], (0.54, 0.77], (0.77, 0.99], (0.096, 0.32]]
Length: 20
Categories (4, interval[float64]): [(0.096, 0.32] < (0.32, 0.54] < (0.54, 0.77] < (0.77, 0.99]]

In [45]:
data = np.random.randn(1000)

In [46]:
data

array([ 0.20312115, -0.38971576, -0.48353349, -0.92549771, -0.08981121,
        0.79886133, -0.70906046,  0.04044397, -0.85044022, -0.67879739,
        0.85707329,  1.69648111, -1.26466172, -1.20588847,  0.66462665,
        1.04391973, -0.20769499,  0.12137958,  0.44147835,  3.33159293,
        0.10465387,  1.42243177, -1.61818797,  0.17069871, -0.73840036,
        0.90289414,  1.6858946 ,  1.70106865,  0.37602514,  0.70835128,
        2.80402675,  1.17564273,  0.66666863, -0.27086936,  0.93123875,
        0.50221332, -1.8928399 ,  0.3860242 ,  0.02951646,  0.82026146,
        0.22182026,  1.27095974,  0.99751183, -0.42397581,  0.22490362,
        2.36988338, -1.27182055,  0.37983569, -1.49095502, -1.22687186,
        2.25238552, -0.4554112 ,  1.15624093, -0.0903784 ,  0.10312053,
       -0.29550092,  0.31984937, -0.76913249, -0.64870597,  0.9361956 ,
       -0.65619655, -2.49255343,  0.95542246,  0.05882355, -0.10322974,
        1.90630716,  0.8635408 ,  0.96306392,  0.19486557, -0.47

In [47]:
cats = pd.qcut(data, 4)

In [48]:
cats

[(0.0132, 0.688], (-0.651, 0.0132], (-0.651, 0.0132], (-3.828, -0.651], (-0.651, 0.0132], ..., (-0.651, 0.0132], (0.688, 3.332], (0.0132, 0.688], (-3.828, -0.651], (-0.651, 0.0132]]
Length: 1000
Categories (4, interval[float64]): [(-3.828, -0.651] < (-0.651, 0.0132] < (0.0132, 0.688] < (0.688, 3.332]]

In [49]:
pd.value_counts(cats)

(0.688, 3.332]      250
(0.0132, 0.688]     250
(-0.651, 0.0132]    250
(-3.828, -0.651]    250
dtype: int64

In [50]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [51]:
data

0         1         2         3
0   -1.381130 -0.356331 -0.098626  1.802365
1   -0.652522  1.193359  1.794364  1.631314
2   -0.388859 -1.921122 -0.786567  1.030471
3   -0.448289 -0.865679  1.107056  1.326829
4   -0.615888  0.894664 -1.332875  0.816284
5   -0.957505 -0.081830 -0.148197  0.460498
6    0.526771  1.271952  1.989603 -0.281142
7    0.889165 -1.062190 -1.076028  0.858386
8    2.207743 -0.915412  0.971159 -1.420878
9   -0.851179 -0.009435 -0.957038 -0.367379
10   0.273200  0.675181 -1.144139  1.071028
11   0.226193 -0.479349  0.272546  1.238975
12  -2.241177  0.444231 -1.352233 -0.008204
13  -0.226582  0.432125 -0.804830 -2.256128
14  -1.402742 -0.634769  0.207209  0.609138
15  -2.113373 -0.368078 -1.522159  0.139253
16   0.736907 -1.822749 -0.771801  1.318658
17  -0.138619  2.644591  0.569825 -0.020669
18   1.018934  0.852774  0.092204 -1.821678
19  -1.207915 -2.136577 -1.989444 -2.011891
20   0.547142 -0.925198 -1.152869 -1.390651
21  -0.525391 -0.414060  0.977270  1.600940
22   2.351583 -0.671074  1.705224  1.261737
23  -0.143178 -0.685658  0.038118  0.006632
24   0.521959 -0.222727  1.131628 -0.037678
25  -0.152872 -0.776569  1.362917  0.869339
26  -0.415967 -1.046279 -0.188004 -0.065260
27  -0.387912  1.002659  1.016895 -0.898151
28   2.003808  1.858777  0.662387 -1.496474
29   0.918285 -0.288178  0.174248 -0.571770
..        ...       ...       ...       ...
970 -1.412614 -0.414254 -0.153346 -0.596794
971 -1.308029 -1.423388 -1.138759  1.309737
972  1.190093 -0.398280 -1.555318  0.988029
973  0.297823 -0.882325  1.383167 -0.206601
974 -1.826863  0.536952  0.973525 -0.712434
975  0.174008 -0.621131  2.768485 -0.305996
976  0.344334  0.491006  0.273321  0.444782
977 -0.992363  2.052016  0.435316  0.996924
978  0.020328  0.723835 -0.068388  1.603985
979 -2.393275  2.392495  0.959997  0.289141
980  1.164770  0.393279 -0.577416 -0.286159
981  0.528047  0.888684  1.522012  1.036910
982  1.069640  0.636857  0.024461  1.587420
983 -0.409422 -1.035405  0.967428 -0.378646
984  0.646470  0.681802  0.722343  0.876982
985 -0.412603 -0.688123 -1.484387 -0.006630
986 -1.565588  0.240593  0.094739 -0.181981
987  0.835841  0.790943  0.549027  0.692571
988 -0.316244 -0.154126 -1.376349 -1.919326
989  1.054419  0.770931  0.266471 -0.884571
990 -0.591003 -0.439549 -0.879442  1.937841
991  1.740999  0.337004 -0.674237 -0.914482
992  1.464975 -1.184814 -1.928019  0.804324
993  1.693588  0.044029 -0.381261 -0.828121
994 -0.744395 -1.162962 -0.480288 -0.011365
995 -2.090562  0.053480 -0.401948  0.194725
996  0.584148  1.337418  0.647814  0.748012
997 -0.584607  0.233883  0.851375 -0.564555
998 -0.780374 -0.353591  0.740706 -0.624149
999 -0.643912 -2.226828 -0.887509 -0.002681

[1000 rows x 4 columns]

In [52]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.006453    -0.010014    -0.011992     0.023900
std       0.995809     0.983670     1.046150     1.027864
min      -2.979705    -3.426355    -3.165257    -3.533410
25%      -0.640314    -0.677396    -0.749559    -0.653908
50%      -0.044659    -0.036874    -0.013994    -0.007835
75%       0.669652     0.628396     0.735618     0.736387
max       2.925601     2.853855     3.777203     3.050656

In [53]:
col = data[2]
col[np.abs(col) > 3]

164    3.777203
237    3.103366
473    3.313534
620   -3.129202
678   -3.165257
Name: 2, dtype: float64

In [54]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [55]:
sampler = np.random.permutation(5)
sampler

array([0, 4, 3, 1, 2])

In [56]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [57]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [58]:
df.sample(n=3)

0  1   2   3
1  4  5   6   7
2  8  9  10  11
0  0  1   2   3

In [59]:
choices = pd.Series([5, 7, -1, 6, 4])

In [60]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [61]:
draws = choices.sample(n=10, replace=True)
draws

0    5
4    4
1    7
4    4
3    6
0    5
2   -1
3    6
3    6
3    6
dtype: int64

In [62]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                       'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [64]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [65]:
df_with_dummpy = df[['data1']].join(dummies)

In [66]:
df_with_dummpy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0